table amostra_evg
	lineageTag: da30a89d-ef65-4406-b681-4d1bce36cdf1

	column cod_matricula
		dataType: string
		lineageTag: 7862d3cc-8723-4a10-b612-f81c3a889eed
		summarizeBy: none
		sourceColumn: cod_matricula

		annotation SummarizationSetBy = Automatic

	column dt_matricula
		dataType: dateTime
		formatString: Long Date
		lineageTag: f294d2e8-cf11-475d-8db2-3a6983d43c6e
		summarizeBy: none
		sourceColumn: dt_matricula

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nacionalidade
		dataType: string
		lineageTag: 76a06315-8f30-4a84-9c50-23d7642742cb
		summarizeBy: none
		sourceColumn: nacionalidade

		annotation SummarizationSetBy = Automatic

	column cod_turma
		dataType: string
		lineageTag: bd6d9bb4-a8ad-4ed3-bbfe-60ca1eb87a2f
		summarizeBy: none
		sourceColumn: cod_turma

		annotation SummarizationSetBy = Automatic

	column nome_turma
		dataType: string
		lineageTag: 86c38b94-1d02-42aa-9b84-8dd92b659843
		summarizeBy: none
		sourceColumn: nome_turma

		annotation SummarizationSetBy = Automatic

	column modalidade_turma
		dataType: string
		lineageTag: ff3ed2b8-1385-4041-8799-790440eace8e
		summarizeBy: none
		sourceColumn: modalidade_turma

		annotation SummarizationSetBy = Automatic

	column cod_curso
		dataType: string
		lineageTag: dbbe8047-0a9f-492f-9869-2570fcec69f4
		summarizeBy: none
		sourceColumn: cod_curso

		annotation SummarizationSetBy = Automatic

	column nome_curso
		dataType: string
		lineageTag: 6b69fa25-5da6-48f5-83e4-89478af274a0
		summarizeBy: none
		sourceColumn: nome_curso

		annotation SummarizationSetBy = Automatic

	column carga_horaria
		dataType: string
		lineageTag: 508ca2c3-4680-41b2-9ad1-ad36317cfb1f
		summarizeBy: none
		sourceColumn: carga_horaria

		annotation SummarizationSetBy = Automatic

	column dt_fim
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0618af0a-7925-4fc9-bb58-acbe539dd8a0
		summarizeBy: none
		sourceColumn: dt_fim

		variation Variation
			isDefault
			relationship: 44123f70-e893-43b6-868e-4ada537e644f
			defaultHierarchy: LocalDateTable_c3ea1774-cf39-4fb8-933c-e564d9930af2.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sit_turma
		dataType: string
		lineageTag: f86e336d-2bbe-400f-a45d-651bdf14834b
		summarizeBy: none
		sourceColumn: sit_turma

		annotation SummarizationSetBy = Automatic

	column instituicao
		dataType: string
		lineageTag: b25eff92-b4da-433c-abc8-7b1eb9a4af82
		summarizeBy: none
		sourceColumn: instituicao

		annotation SummarizationSetBy = Automatic

	column municipio_pessoa
		dataType: string
		lineageTag: fbdfd3ca-1e60-43f0-a74f-95b915290c32
		summarizeBy: none
		sourceColumn: municipio_pessoa

		annotation SummarizationSetBy = Automatic

	column uf_pessoa
		dataType: string
		lineageTag: c8cc7bda-3b8a-42a0-bd94-0e69ce8fef9f
		summarizeBy: none
		sourceColumn: uf_pessoa

		annotation SummarizationSetBy = Automatic

	column conteudista
		dataType: string
		lineageTag: 2289daba-ab15-4cb2-a0b9-f98c5a813ded
		summarizeBy: none
		sourceColumn: conteudista

		annotation SummarizationSetBy = Automatic

	column tematica
		dataType: string
		lineageTag: 8bb173af-cedc-4c75-8dd2-58b4cf9366fc
		summarizeBy: none
		sourceColumn: tematica

		annotation SummarizationSetBy = Automatic

	column codigo_pessoa
		dataType: string
		lineageTag: 81ab47d1-76b6-487d-b94d-5acf9aa290fc
		summarizeBy: none
		sourceColumn: codigo_pessoa

		annotation SummarizationSetBy = Automatic

	column sexo
		dataType: string
		lineageTag: b76f2a89-e087-4f9f-a746-19fc322c874d
		summarizeBy: none
		sourceColumn: sexo

		annotation SummarizationSetBy = Automatic

	column idade
		dataType: string
		lineageTag: ccbf15bc-c196-4697-a030-02d103dc08fb
		summarizeBy: none
		sourceColumn: idade

		annotation SummarizationSetBy = Automatic

	column sit_matricula
		dataType: string
		lineageTag: 99656c2e-e8bb-4fde-81a3-90e60d0d484a
		summarizeBy: none
		sourceColumn: sit_matricula

		annotation SummarizationSetBy = Automatic

	column poder
		dataType: string
		lineageTag: 5e2414a5-a456-4b33-b0a0-b31b873d3dff
		summarizeBy: none
		sourceColumn: poder

		annotation SummarizationSetBy = Automatic

	column esfera
		dataType: string
		lineageTag: 2eac0e37-c33f-4eae-bd80-9a529e4dd589
		summarizeBy: none
		sourceColumn: esfera

		annotation SummarizationSetBy = Automatic

	column email_pessoa
		dataType: string
		lineageTag: 0b0614aa-d55a-4bb3-ae12-5aae4b16e8a6
		summarizeBy: none
		sourceColumn: email_pessoa

		annotation SummarizationSetBy = Automatic

	column telefone_pessoa
		dataType: string
		lineageTag: cd041503-96f3-4cd3-8243-f948d4d3da28
		summarizeBy: none
		sourceColumn: telefone_pessoa

		annotation SummarizationSetBy = Automatic

	column email_conteudista
		dataType: string
		lineageTag: e948ed26-dc6b-4ad1-b9c8-d5537f6ceff2
		summarizeBy: none
		sourceColumn: email_conteudista

		annotation SummarizationSetBy = Automatic

	partition amostra_evg = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\renata.teixeira\Downloads\amostra_evg.csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"dt_matricula", type datetime}, {"dt_fim", type datetime}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado",{{"dt_fim", type date}, {"dt_matricula", type date}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

