table Dcalendar
	lineageTag: c8aa84dd-ba9c-40e4-82a9-fc9dbf084e66

	column data
		dataType: dateTime
		formatString: Long Date
		lineageTag: f0c24e75-7f0a-4a09-b0c3-d7689f5e54e6
		summarizeBy: none
		sourceColumn: data

		variation Variation
			isDefault
			relationship: e7a7c222-4f60-411d-863b-70ad35cb67de
			defaultHierarchy: LocalDateTable_d394bc4b-f987-4dfb-85e9-625d180bebc4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 12723e1a-4619-4d7d-ac70-4c1bad82f424
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 98794fe6-43be-4bf5-a3a9-fa80480c148d
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: dcd39cb1-646c-403d-9afa-00adf0f019d6
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: ab0f94bf-8a1c-4041-9cc6-4dfb4ff0ebe8
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 08dfcc96-db7c-4fd6-9e10-97c9f56f87cd
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: debed80c-268a-460e-942e-7bcadd5cb173
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	partition Dcalendar = m
		mode: import
		source =
				let
				    Fonte = "",
				    DtMin = List.Min(amostra_evg[dt_matricula]),
				    DtMax = List.Max(amostra_evg[dt_matricula]),
				    Ndias = Duration.Days(DtMax - DtMin) + 1,
				    Personalizar1 = List.Dates(DtMin, Ndias, #duration(1,0,0,0)),
				    #"Convertido para Tabela" = Table.FromList(Personalizar1, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Trimestre", each Date.QuarterOfYear([data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Trimestre Inserido", "Dia", each Date.Day([data]), Int64.Type),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Dia Inserido",{"data", "Ano", "Mês", "Dia", "Nome do Mês", "Trimestre"}),
				    #"Dia da Semana Inserido" = Table.AddColumn(#"Colunas Reordenadas", "Dia da Semana", each Date.DayOfWeek([data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia da Semana Inserido", "Nome do Dia", each Date.DayOfWeekName([data]), type text),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Nome do Dia Inserido",{"Dia da Semana"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

